# Generated by Django 5.1.5 on 2025-02-12 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
        ('userProfile', '0003_userprofile_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['createdAt']},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='is_read',
            new_name='isRead',
        ),
        migrations.RemoveField(
            model_name='message',
            name='thread',
        ),
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='userProfile.userprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='userProfile.userprofile'),
        ),
    ]
