# Generated by Django 5.1.5 on 2025-02-12 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-createdAt']},
        ),
    ]
