# Generated by Django 5.1.5 on 2025-02-09 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='gigId',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='swaprequest',
            name='swapId',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
