# Generated by Django 5.1.5 on 2025-02-09 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0002_gig_gigid_swaprequest_swapid'),
        ('userProfile', '0002_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userProfile.userprofile'),
        ),
    ]
