# Generated by Django 5.1.5 on 2025-02-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0003_alter_gig_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='desiredSkills',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='gig',
            name='offeredSkills',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
