# Generated by Django 5.1.5 on 2025-02-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0004_alter_gig_desiredskills_alter_gig_offeredskills'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='tags',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
