# Generated by Django 5.0.7 on 2025-03-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0006_alter_swaprequest_requestor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gig',
            name='impressions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gig',
            name='swaps',
            field=models.IntegerField(default=0),
        ),
    ]
