# Generated by Django 5.0.7 on 2025-03-23 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0007_gig_clicks_gig_impressions_gig_swaps'),
        ('userProfile', '0003_userprofile_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwapDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('requestor_file', models.FileField(blank=True, null=True, upload_to='swap_deliveries/requestor/')),
                ('requestor_status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('accepted', 'Accepted')], default='pending', max_length=20)),
                ('requestor_delivered_at', models.DateTimeField(blank=True, null=True)),
                ('requestor_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('responder_file', models.FileField(blank=True, null=True, upload_to='swap_deliveries/responder/')),
                ('responder_status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('accepted', 'Accepted')], default='pending', max_length=20)),
                ('responder_delivered_at', models.DateTimeField(blank=True, null=True)),
                ('responder_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('swap_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='gigs.swaprequest')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to='swap_comments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userProfile.userprofile')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='gigs.swapdelivery')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
