# Generated by Django 5.0.7 on 2025-03-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0008_swapdelivery_deliverycomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='swapdelivery',
            name='requestor_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='swapdelivery',
            name='responder_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
